services:
  web:
    container_name: appbase64
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports:
      - "27018:27017"