services:
  web:
    container_name: appbase64
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
    volumes:
      - .:/home/node/app
    environment: 
      BD_CNN: mongodb://mongo:27017/files
      PORT: 3000
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none